services:
    akeneo_file_storage.query.find_key_by_hash:
        class: 'Akeneo\Tool\Bundle\FileStorageBundle\Doctrine\ORM\Query\FindKeyByHashQuery'
        arguments:
            - '@database_connection'
