version: '3'

services:
  fpm:
    image: 'akeneo/fpm:php-7.2'
    user: 'docker'
    volumes:
      - './:/srv/pim'
    working_dir: '/srv/pim'
    networks:
      - 'akeneo'

  node:
    image: 'akeneo/node:10'
    user: 'node'
    volumes:
      - './:/srv/pim'
    working_dir: '/srv/pim'
    networks:
      - 'akeneo'

  selenium:
    image: 'selenium/standalone-firefox-debug:2.53.1-beryllium'
    volumes:
      - './:/srv/pim:ro'
    networks:
      - 'akeneo'

  httpd:
    image: 'httpd:2.4'
    depends_on:
      - 'fpm'
    ports:
      - '${DOCKER_PORT_HTTP}:80'
      - '${DOCKER_PORT_HTTP_BEHAT}:8080'
    volumes:
      - './:/srv/pim:ro'
      - './docker/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro'
      - './docker/akeneo.conf:/usr/local/apache2/conf/akeneo_vhost.conf:ro'
      - './docker/akeneo-behat.conf:/usr/local/apache2/conf/akeneo-behat_vhost.conf:ro'
    networks:
      - 'akeneo'

  mysql:
    image: 'mysql:5.7'
    volumes:
      - './docker/init_dbs.sql:/docker-entrypoint-initdb.d/init_dbs.sql:ro'
    networks:
      - 'akeneo'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4'
    environment:
      ES_JAVA_OPTS: '${ES_JAVA_OPTS:--Xms512m -Xmx512m}'
      discovery.type: 'single-node'
    networks:
      - 'akeneo'

  object-storage:
    image: 'minio/minio'
    entrypoint: '/bin/sh -c "mkdir -p /data/archive /data/catalog/ /data/jobs && minio server /data"'
    environment:
      MINIO_ACCESS_KEY: 'AKENEO_OBJECT_STORAGE_ACCESS_KEY'
      MINIO_SECRET_KEY: 'AKENEO_OBJECT_STORAGE_SECRET_KEY'
    networks:
      - 'akeneo'

networks:
  akeneo:
